version: '2'

services:
  server:
    build:
      context: ./docker
      args:
        project_name: hello
    image: golang_glide
    container_name: go_dev_glide
    entrypoint: 
      - /go/bin/hello
    env_file: environment.env
    volumes:
      - ./:/go
    ports:
      - "8080:8080"
