version: '2'

services:
  server:
    image: golang
    container_name: go_dev
    entrypoint: 
      - /go/bin/hello
    env_file: environment.env
    volumes:
      - ./:/go
      - ./docker/scripts:/scripts
    ports:
      - "8080:8080"
