version: '2'

services:
  server:
    build:
      context: ./docker
    image: go_dev
    container_name: golang_dev
    entrypoint:
      - /go/bin/hello
    env_file: environment.env
    volumes:
      - ./src:/go
      - ./docker/scripts:/scripts
    ports:
      - "8080:8080"
